services:
  app:
    container_name: my_project_app
    build: ./
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - project_db

  project_db:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - project_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_ready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  project_db_data:
